#!/bin/bash

# Bash
rm -f ~/.bash_aliases&& ln -s ~/Projects/dotfiles/bash/bash_aliases ~/.bash_aliases
rm -f ~/.bash_profile && ln -s ~/Projects/dotfiles/bash/bash_profile ~/.bash_profile
rm -f ~/.bashrc && ln -s ~/Projects/dotfiles/bash/bashrc ~/.bashrc

# Git
rm -f ~/.gitconfig && ln -s ~/Projects/dotfiles/git/gitconfig ~/.gitconfig