# If not running interactively, don't do anything
[ -z "$PS1" ] && return

HISTCONTROL=erasedups
HISTIGNORE="pwd*:ls*:ll*:exit*:history*:clear*"

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Load aliases, if any are specified.
if [ -f ~/.bash_aliases ] ; then
    . ~/.bash_aliases
fi

# Load bin directory, if exists.
if [ -d ~/bin ] ; then
    PATH=~/bin:"${PATH}"
fi

# Load git-completion, if exists.
if [ -f ~/bin/git-completion.bash ] ; then
    . ~/bin/git-completion.bash
fi

PATH=/usr/local/bin:/usr/local/sbin:$PATH

PS1="\e[0;31m[\t]\e[0m \e[0;37m\u@\h\e[0m \e[0;32m\w\e[0m\$(__git_ps1)\n$ "
